// ============================================================
// Chart of Accounts — Default Seed Data for Ambrits Training Hub
// ============================================================

import type { Account } from '../types';

export const defaultAccounts: Account[] = [
  // ─── ASSETS ─────────────────────────────────────────────
  // Cash in Hand
  { id: 'acc-1100', accountCode: '1100', accountName: 'Cash in Hand', accountType: 'asset', accountGroup: 'cash_in_hand', normalBalance: 'debit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Physical cash held at the office' },
  // Bank Account
  { id: 'acc-1110', accountCode: '1110', accountName: 'Bank Account', accountType: 'asset', accountGroup: 'bank_account', normalBalance: 'debit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Primary bank account' },
  // Payment Gateway Receivable
  { id: 'acc-1120', accountCode: '1120', accountName: 'Payment Gateway Receivable', accountType: 'asset', accountGroup: 'payment_gateway_receivable', normalBalance: 'debit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Pending settlements from payment gateways' },
  // Student Receivables
  { id: 'acc-1200', accountCode: '1200', accountName: 'Student Receivables', accountType: 'asset', accountGroup: 'student_receivables', normalBalance: 'debit', courseRequired: true, isSystemAccount: true, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Amounts due from students for course fees' },
  // Inventory
  { id: 'acc-1300', accountCode: '1300', accountName: 'Inventory', accountType: 'asset', accountGroup: 'inventory', normalBalance: 'debit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Study materials and other inventory' },
  // Advance to Vendors
  { id: 'acc-1400', accountCode: '1400', accountName: 'Advance to Vendors', accountType: 'asset', accountGroup: 'advance_to_vendors', normalBalance: 'debit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Advance payments made to vendors' },
  // Input GST
  { id: 'acc-1500', accountCode: '1500', accountName: 'Input GST', accountType: 'asset', accountGroup: 'input_gst', normalBalance: 'debit', courseRequired: false, isSystemAccount: true, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'GST paid on purchases (input tax credit)' },
  // Fixed Assets
  { id: 'acc-1600', accountCode: '1600', accountName: 'Fixed Assets', accountType: 'asset', accountGroup: 'fixed_assets', normalBalance: 'debit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Long-term tangible assets' },
  // Accumulated Depreciation
  { id: 'acc-1700', accountCode: '1700', accountName: 'Accumulated Depreciation', accountType: 'asset', accountGroup: 'accumulated_depreciation', normalBalance: 'credit', courseRequired: false, isSystemAccount: true, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Cumulative depreciation on fixed assets' },

  // ─── LIABILITIES ────────────────────────────────────────
  // Student Advances
  { id: 'acc-2000', accountCode: '2000', accountName: 'Student Advances', accountType: 'liability', accountGroup: 'student_advances', normalBalance: 'credit', courseRequired: false, isSystemAccount: true, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Advance payments received from students' },
  // Accounts Payable
  { id: 'acc-2100', accountCode: '2100', accountName: 'Accounts Payable', accountType: 'liability', accountGroup: 'accounts_payable', normalBalance: 'credit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Amounts owed to vendors and suppliers' },
  // Output GST Payable
  { id: 'acc-2200', accountCode: '2200', accountName: 'Output GST Payable', accountType: 'liability', accountGroup: 'output_gst_payable', normalBalance: 'credit', courseRequired: false, isSystemAccount: true, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'GST collected on sales (output tax)' },
  // TDS Payable
  { id: 'acc-2300', accountCode: '2300', accountName: 'TDS Payable', accountType: 'liability', accountGroup: 'tds_payable', normalBalance: 'credit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Tax deducted at source payable' },
  // Salary Payable
  { id: 'acc-2350', accountCode: '2350', accountName: 'Salary Payable', accountType: 'liability', accountGroup: 'salary_payable', normalBalance: 'credit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Salaries owed to employees' },
  // Trainer Payable
  { id: 'acc-2360', accountCode: '2360', accountName: 'Trainer Payable', accountType: 'liability', accountGroup: 'trainer_payable', normalBalance: 'credit', courseRequired: true, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Payments owed to trainers' },
  // Counsellor Incentive Payable
  { id: 'acc-2400', accountCode: '2400', accountName: 'Counsellor Incentive Payable', accountType: 'liability', accountGroup: 'counsellor_incentive_payable', normalBalance: 'credit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Incentive amounts owed to counsellors' },
  // Referral Reward Payable
  { id: 'acc-2500', accountCode: '2500', accountName: 'Referral Reward Payable', accountType: 'liability', accountGroup: 'referral_reward_payable', normalBalance: 'credit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Referral reward amounts owed' },
  // Other Current Liabilities
  { id: 'acc-2900', accountCode: '2900', accountName: 'Other Current Liabilities', accountType: 'liability', accountGroup: 'other_current_liabilities', normalBalance: 'credit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Other short-term liabilities' },

  // ─── INCOME ─────────────────────────────────────────────
  { id: 'acc-4000', accountCode: '4000', accountName: 'IELTS Course Revenue', accountType: 'income', accountGroup: 'course_revenue', normalBalance: 'credit', courseRequired: true, isSystemAccount: true, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Revenue from IELTS courses' },
  { id: 'acc-4010', accountCode: '4010', accountName: 'PTE Course Revenue', accountType: 'income', accountGroup: 'course_revenue', normalBalance: 'credit', courseRequired: true, isSystemAccount: true, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Revenue from PTE courses' },
  { id: 'acc-4020', accountCode: '4020', accountName: 'Duolingo Course Revenue', accountType: 'income', accountGroup: 'course_revenue', normalBalance: 'credit', courseRequired: true, isSystemAccount: true, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Revenue from Duolingo courses' },
  { id: 'acc-4030', accountCode: '4030', accountName: 'English Course Revenue', accountType: 'income', accountGroup: 'course_revenue', normalBalance: 'credit', courseRequired: true, isSystemAccount: true, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Revenue from English speaking courses' },
  { id: 'acc-4040', accountCode: '4040', accountName: 'Foundation English Revenue', accountType: 'income', accountGroup: 'course_revenue', normalBalance: 'credit', courseRequired: true, isSystemAccount: true, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Revenue from Foundation English courses' },
  { id: 'acc-4050', accountCode: '4050', accountName: 'GRE Revenue', accountType: 'income', accountGroup: 'course_revenue', normalBalance: 'credit', courseRequired: true, isSystemAccount: true, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Revenue from GRE courses' },
  { id: 'acc-4060', accountCode: '4060', accountName: 'LanguageCert Revenue', accountType: 'income', accountGroup: 'course_revenue', normalBalance: 'credit', courseRequired: true, isSystemAccount: true, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Revenue from LanguageCert courses' },
  { id: 'acc-4100', accountCode: '4100', accountName: 'Mock-Test Revenue', accountType: 'income', accountGroup: 'mock_test_revenue', normalBalance: 'credit', courseRequired: false, isSystemAccount: true, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Revenue from mock tests' },
  { id: 'acc-4110', accountCode: '4110', accountName: 'Exam-Slot Revenue', accountType: 'income', accountGroup: 'exam_slot_revenue', normalBalance: 'credit', courseRequired: false, isSystemAccount: true, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Revenue from exam slot bookings' },
  { id: 'acc-4200', accountCode: '4200', accountName: 'Course-Addon Revenue', accountType: 'income', accountGroup: 'course_addon_revenue', normalBalance: 'credit', courseRequired: false, isSystemAccount: true, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Revenue from course add-ons' },
  { id: 'acc-4300', accountCode: '4300', accountName: 'Study-Material Revenue', accountType: 'income', accountGroup: 'study_material_revenue', normalBalance: 'credit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Revenue from study material sales' },
  { id: 'acc-4400', accountCode: '4400', accountName: 'Registration Revenue', accountType: 'income', accountGroup: 'registration_revenue', normalBalance: 'credit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Revenue from registration charges' },
  { id: 'acc-4900', accountCode: '4900', accountName: 'Other Operating Income', accountType: 'income', accountGroup: 'other_operating_income', normalBalance: 'credit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Miscellaneous operating income' },

  // ─── EXPENSES ───────────────────────────────────────────
  { id: 'acc-5100', accountCode: '5100', accountName: 'Trainer Payments', accountType: 'expense', accountGroup: 'trainer_payments', normalBalance: 'debit', courseRequired: true, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Payments to trainers for course delivery' },
  { id: 'acc-5110', accountCode: '5110', accountName: 'Salaries', accountType: 'expense', accountGroup: 'salaries', normalBalance: 'debit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Staff salaries' },
  { id: 'acc-5200', accountCode: '5200', accountName: 'Counsellor Incentives', accountType: 'expense', accountGroup: 'counsellor_incentives', normalBalance: 'debit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Incentive payments to counsellors' },
  { id: 'acc-5300', accountCode: '5300', accountName: 'Referral Rewards', accountType: 'expense', accountGroup: 'referral_rewards_expense', normalBalance: 'debit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Referral reward expenses' },
  { id: 'acc-5400', accountCode: '5400', accountName: 'Advertising', accountType: 'expense', accountGroup: 'advertising', normalBalance: 'debit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Marketing and advertising expenses' },
  { id: 'acc-5500', accountCode: '5500', accountName: 'Office Rent', accountType: 'expense', accountGroup: 'office_rent', normalBalance: 'debit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Office space rental' },
  { id: 'acc-5510', accountCode: '5510', accountName: 'Electricity', accountType: 'expense', accountGroup: 'electricity', normalBalance: 'debit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Electricity expenses' },
  { id: 'acc-5520', accountCode: '5520', accountName: 'Internet', accountType: 'expense', accountGroup: 'internet', normalBalance: 'debit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Internet and connectivity' },
  { id: 'acc-5530', accountCode: '5530', accountName: 'Telephone', accountType: 'expense', accountGroup: 'telephone', normalBalance: 'debit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Telephone and communication' },
  { id: 'acc-5600', accountCode: '5600', accountName: 'Teaching Materials', accountType: 'expense', accountGroup: 'teaching_materials', normalBalance: 'debit', courseRequired: true, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Materials used in teaching' },
  { id: 'acc-5610', accountCode: '5610', accountName: 'Inventory Consumption', accountType: 'expense', accountGroup: 'inventory_consumption', normalBalance: 'debit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Inventory consumed in operations' },
  { id: 'acc-5700', accountCode: '5700', accountName: 'Software Subscriptions', accountType: 'expense', accountGroup: 'software_subscriptions', normalBalance: 'debit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'SaaS and software costs' },
  { id: 'acc-5710', accountCode: '5710', accountName: 'Payment Gateway Charges', accountType: 'expense', accountGroup: 'payment_gateway_charges', normalBalance: 'debit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Fees charged by payment gateways' },
  { id: 'acc-5720', accountCode: '5720', accountName: 'Bank Charges', accountType: 'expense', accountGroup: 'bank_charges', normalBalance: 'debit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Bank service charges' },
  { id: 'acc-5800', accountCode: '5800', accountName: 'Repairs and Maintenance', accountType: 'expense', accountGroup: 'repairs_maintenance', normalBalance: 'debit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Repair and maintenance costs' },
  { id: 'acc-5810', accountCode: '5810', accountName: 'Professional Fees', accountType: 'expense', accountGroup: 'professional_fees', normalBalance: 'debit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'CA, legal, and professional fees' },
  { id: 'acc-5820', accountCode: '5820', accountName: 'Printing and Stationery', accountType: 'expense', accountGroup: 'printing_stationery', normalBalance: 'debit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Printing and stationery costs' },
  { id: 'acc-5830', accountCode: '5830', accountName: 'Travel and Conveyance', accountType: 'expense', accountGroup: 'travel_conveyance', normalBalance: 'debit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Travel and conveyance expenses' },
  { id: 'acc-5850', accountCode: '5850', accountName: 'Depreciation', accountType: 'expense', accountGroup: 'depreciation', normalBalance: 'debit', courseRequired: false, isSystemAccount: true, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Depreciation on fixed assets' },
  { id: 'acc-5900', accountCode: '5900', accountName: 'Other Expenses', accountType: 'expense', accountGroup: 'other_expenses', normalBalance: 'debit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Miscellaneous expenses' },

  // ─── EQUITY ─────────────────────────────────────────────
  { id: 'acc-3000', accountCode: '3000', accountName: 'Capital Account', accountType: 'equity', accountGroup: 'capital_account', normalBalance: 'credit', courseRequired: false, isSystemAccount: true, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Owner\'s capital contribution' },
  { id: 'acc-3100', accountCode: '3100', accountName: 'Owner\'s Drawings', accountType: 'equity', accountGroup: 'owners_drawings', normalBalance: 'debit', courseRequired: false, isSystemAccount: false, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Amounts withdrawn by the owner' },
  { id: 'acc-3200', accountCode: '3200', accountName: 'Retained Earnings', accountType: 'equity', accountGroup: 'retained_earnings', normalBalance: 'credit', courseRequired: false, isSystemAccount: true, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Accumulated profits retained in the business' },
  { id: 'acc-3300', accountCode: '3300', accountName: 'Current-Year Profit or Loss', accountType: 'equity', accountGroup: 'current_year_pl', normalBalance: 'credit', courseRequired: false, isSystemAccount: true, isActive: true, openingBalance: 0, createdBy: 'system', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), description: 'Current financial year profit or loss' },
];
